spring.application.name=be-order
server.port=${ORDER_APP_PORT:5002}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:dev-order-jwt-secret-dev-order-jwt-secret-123456}

order.inventory.url=${ORDER_INVENTORY_URL:http://localhost:4002/api/products}
order.inventory.internal-role=${ORDER_INVENTORY_INTERNAL_ROLE:ADMIN}
order.inventory.internal-user-id=${ORDER_INVENTORY_INTERNAL_USER_ID:order-service}
order.wallet.url=${ORDER_WALLET_URL:http://localhost:6002/api/contracts/wallet}
order.wallet.internal-authorization=${ORDER_WALLET_INTERNAL_AUTHORIZATION:Bearer internal-order-service}
order.wallet.grpc.host=${ORDER_WALLET_GRPC_HOST:localhost}
order.wallet.grpc.port=${ORDER_WALLET_GRPC_PORT:9090}
order.wallet.grpc.internal-token=${GRPC_SERVER_INTERNAL_TOKEN:}
order.voucher.url=${ORDER_VOUCHER_URL:http://localhost:7002/api/vouchers}
order.profile.url=${ORDER_PROFILE_URL:http://localhost:3002/api/profile}
order.profile.internal-authorization=${ORDER_PROFILE_INTERNAL_AUTHORIZATION:}
order.http.retry.max-attempts=2
order.http.timeout.connect-ms=2000
order.http.timeout.read-ms=4000
